---
name: "Meta: Mark or close stale issues and PRs"
on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.TOKEN }}
          days-before-issue-stale: 60
          days-before-pr-stale: 30
          days-before-close: 7
          days-before-pr-close: 14
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed in a week if no further activity occurs.
            Thank you for your contributions.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in two weeks if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: >
            This issue has been automatically closed due to inactivity.
            Please re-open if this still requires investigation.
          close-pr-message: >
            This pull request has been automatically closed due to inactivity.
            Please re-open if these changes are still required.
          stale-pr-label: stale
          stale-issue-label: stale
          exempt-issue-labels: keepalive
          exempt-pr-labels: keepalive
