---
name: "Meta: Support Requests"

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-22.04
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ secrets.TOKEN }}
          support-label: support
          issue-comment: |
            :wave: @{issue-author}, we use the issue tracker exclusively for bug reports and feature requests. 
            This issue appears to be a support request, please use our support channels to get help:

            - [Docs](https://docs.k8s-at-home.com/)
            - [Discord](https://discord.gg/k8s-at-home)
            - [GitHub Discussions](https://github.com/k8s-at-home/organization/discussions)
          close-issue: true
          lock-issue: false
          issue-lock-reason: off-topic
