---
name: "Manual Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App (ex: radarr)"
        default: ""
        required: true
      channels:
        description: "Channels (ex: master,develop)"
        default: ""
        required: true
      push:
        description: "Push"
        type: boolean
        default: true
        required: true

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  determine-images:
    name: Determine Images to Build
    runs-on: ubuntu-latest
    outputs:
      appsToBuild: ${{ steps.determine-images.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Determine images to build
        id: determine-images
        shell: bash
        run: |
          if [ "${{ inputs.app }}" = "ALL" ]; then
            ./.github/scripts/fetch.sh all
          else
            output="[]"
            IFS=',' read -a channels <<< "${{ inputs.channels }}"
            declare -a images_array=()
            for channel in "${channels[@]}"; do
              image="$(jo app="${{ inputs.app }}" channel="$channel")"
              images_array+=($image)
            done

            output="$(jo -a ${images_array[*]})"
            echo "changes=${output}" >> $GITHUB_OUTPUT
            echo "Changes:\n ${output}"
          fi

  images-build:
    uses: ./.github/workflows/build-images.yaml
    if: needs.determine-images.outputs.appsToBuild != '[]'
    needs: ["determine-images"]
    with:
      appsToBuild: "${{ needs.determine-images.outputs.appsToBuild }}"
      pushImages: ${{ github.event.inputs.push }}
    secrets: inherit
